require:
    - rubocop-rails

AllCops:
    Exclude:
        - bin/*
        - db/schema.rb
        - vendor/**/*
        - Gemfile
        - Guardfile
        - Rakefile

Rails:
    Enabled: true

#Documentation:
#    Exclude:
#        - 'db/migrate/*'

Metrics/MethodLength:
    Exclude:
        - 'db/migrate/*'

Metrics/AbcSize:
    Exclude:
        - 'db/migrate/*'

# "Missing top-level class documentation comment."を無効
Style/Documentation:
    Enabled: false

Style/AsciiComments:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/PredicateName:
    Enabled: false

Style/StringLiterals:
    EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
    Enabled: false

##################### Metrics ##################################

# 30 まではギリギリ許せる範囲だった
Metrics/AbcSize:
  Max: 30

# 6 は強すぎるので緩める
Metrics/CyclomaticComplexity:
  Max: 10

# * 警告 120文字
# * 禁止 160文字
# のイメージ
Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

# 20 行超えるのは migration ファイル以外滅多に無い
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

# testはブロックあたりの行数を無視する
Metrics/BlockLength:
    Exclude:
     - "test/**/*"

# 分岐の数。ガード句を多用しているとデフォルト 7 だと厳しい
Metrics/PerceivedComplexity:
  Max: 8

####### Rails ####################################

Rails/SkipsModelValidations:
    AllowedMethods:
    - update_attribute
